[Pathes]
    python              = /home/<workdir>/bin/python3.13
    java                = /usr/lib/jvm/default-runtime/bin/java

    bwa-mem2            = /home/<workdir>/<tools>/bwa-mem2-2.2.1_x64-linux/bwa-mem2
    samtools            = /home/<workdir>/<tools>/samtools-1.22/samtools
    bedtools            = /home/<workdir>/<tools>/bedtools-2.31.1/bedtools2/bin/bedtools
    picard              = /home/<workdir>/<tools>/picard/picard.jar
    gatk                = /home/<workdir>/<tools>/gatk-4.6.2.0/gatk

    freebayes           = /home/<workdir>/<tools>/freebayes-1.3.10/freebayes-1.3.10-linux-amd64-static
    pisces              = /home/<workdir>/<tools>/pisces_all/Pisces
    snpeff              = /home/<workdir>/<tools>/snpEff/snpEff.jar

    trimmomatic         = /home/<workdir>/<tools>/Trimmomatic-0.39/trimmomatic-0.39.jar

    ptrimmer            = /home/<workdir>/<tools>/pTrimmer/pTrimmer
    ampfile             = /home/<workdir>/<static>/ampfile.txt

    cutprimers          = /home/<workdir>/<tools>/cutPrimers/cutPrimers.py
    primer15            = /home/<workdir>/<tools>/cutPrimers/example/primers_R1_5.fa
    primer13            = /home/<workdir>/<tools>/cutPrimers/example/primers_R1_3.fa
    primer25            = /home/<workdir>/<tools>/cutPrimers/example/primers_R2_5.fa
    primer23            = /home/<workdir>/<tools>/cutPrimers/example/primers_R2_3.fa

    reference-directory = /home/<workdir>/<static>/ref
    reference           = /home/<workdir>/<static>/ref/ucsc.hg19/ucsc.hg19.fa
    annotation-database = /home/<workdir>/<static>/annotation_databases/clinvar_20250806.vcf

    convert2annovar     = /home/<workdir>/<tools>/annovar/convert2annovar.pl
    table_annovar       = /home/<workdir>/<tools>/annovar/table_annovar.pl
    annovar_humandb     = /home/<workdir>/<tools>/annovar/humandb

    reads-dir           = /home/<workdir>/<static>/<reeds_dir>

[Regions] ; hg19/GRCh37
    chr01-interval      = chr1:1-249250621
    chr02-interval      = chr2:1-243199373
    chr03-interval      = chr3:1-198022430
    chr06-interval      = chr6:1-171115067
    chr07-interval      = chr7:1-159138663
    chr08-interval      = chr8:1-146364022
    chr09-interval      = chr9:1-141213431
    chr10-interval      = chr10:1-135534747
    chr11-interval      = chr11:1-135006516
    chr12-interval      = chr12:1-133851895
    chr13-interval      = chr13:1-115169878
    chr14-interval      = chr14:1-107349540
    chr15-interval      = chr15:1-101512524
    chr16-interval      = chr16:1-90295280
    chr17-interval      = chr17:1-81195210
    chr18-interval      = chr18:1-80377344
    chr19-interval      = chr19:1-58617616
    chr20-interval      = chr20:1-64444167
    chr21-interval      = chr21:1-46709983
    chr22-interval      = chr22:1-50818468
    chrX-interval       = chrX:155270560
    chrY-interval       = chrY:1-59373566

    gene-CCDC57         = 17:80059346-80170718
    gene-SNG20          = 17:75082798-75095984
    gene-NBR2           = 17:41277568-41305666
    gene-BRCA1          = 17:41196312-41277381
    gene-DCT            = 13:95089065-95131936
    gene-BRCA2          = 13:32889645-32974405

[Trimmomatic]
    ; For more details about Trimmomatic configuration options see https://github.com/usadellab/Trimmomatic/blob/main/README.md
    phred               = phred33 ; phred33 or phred64 are availible as valid options
    adapters            = /home/<workdir>/<tools>/Trimmomatic-0.39/adapters/adapters.fastq
    illuminaclip        = 2:30:10 ; Cut adapter and other illumina-specific sequences from the read
    leading             = 3       ; Cut bases off the start of a read, if below a threshold quality
    trailing            = 3       ; Cut bases off the end of a read, if below a threshold quality
    slidingwindow       = 4:15    ; Perform a sliding window trimming, cutting once the average quality within the window falls below a threshold
    ;minlen             =         ; Drop the read if it is below a specified length
    ;crop               =         ; Cut the read to a specified length
    ;headcrop           =         ; Cut the specified number of bases from the start of the read

[TableManager] ; Support .csv, .tsv, .xls, .xlsx, .xml formats of input files
    adapter-list        = /home/<workdir>/<static>/adapters_with_index.xls
    index-list          = /home/<workdir>/<static>/all_indices_for_NGS_libs.xlsx
    sample-list         = /home/<workdir>/<static>/sample_list.xlsx

    sample-sheet        = /home/<workdir>/<static>/Sample_sheet__sampleInfo.csv ; Demultiplexing process dependency
    dump-file           = /home/<workdir>/<static>/dump.csv

    base_outpath        = /home/<workdir>/<static>/<run_name>

[DemultiplexorAdapter]
    demultiplexor   = /home/<workdir>/<tools>/bcl2fastq2/usr/local/bin/bcl2fastq
    min-log-level   = INFO

    runfolder-dir	= /home/<workdir>/<static>/<run_name>
    input-dir		= /home/<workdir>/<static>/<run_name>/Data/Intensities/BaseCalls
    output-dir		= /home/<workdir>/<static>/refactored_demultiplexor
    intensities-dir = /home/<workdir>/<static>/<run_name>/Data/Intensities

    interop-dir     = /home/<workdir>/<static>/<run_name>/demultiplexed/interop
    reports-dir		= /home/<workdir>/<static>/<run_name>/demultiplexed/report
    stats-dir       = /home/<workdir>/<static>/<run_name>/demultiplexed/stats

    sample-sheet	= /home/<workdir>/<static>/sample_sheet.csv

    tiles			                 = s_*
    use-bases-mask                   = Y*,I*,I*,Y*

    loading-threads		             = 8
    processing-threads	             = 8
    writing-threads		             = 8
    minimum-trimmed-read-length      = 35
    mask-short-adapter-reads	     = 22
    adapter-stringency			     = 0.9
    fastq-compression-level		     = 4
    barcode-mismatches			     = 1

    ignore-missing-bcls			     = True
    ignore-missing-filter		     = True
    ignore-missing-positions	     = False
    ignore-missing-controls		     = False
    write-fastq-reverse-complement   = False
    with-failed-reads			     = False
    create-fastq-for-index-reads     = False
    find-adapters-with-sliding-window= False
    no-bgzf-compression			     = True
    no-lane-splitting                = False

[samtools]
    min-BQ                           = 0
    max-depth                        = 1000000
    coords-file                      = /home/<workdir>/<static>/coords.tsv
